/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ExemplaireController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Asus
 */
public class ExemplaireView extends javax.swing.JInternalFrame {

       
    
    ExemplaireController controller=new ExemplaireController();
    
    String CodeBare;
    double Prix;
    String DateAchat;
    int IdDoc;
    SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
    
    
    DefaultComboBoxModel cmbModel;
    
    
    
    public ExemplaireView() {
        initComponents();
        initTable();
        initComboBox();   
    }
    
    public void initComboBox(){
        cmbModel = new DefaultComboBoxModel();
        
        try {
            controller.getModel().setResultSet(controller.getDao().getRsAll());
            String colname[]=new String[controller.getModel().getColumnCount()];
            for(int i=0;i<controller.getModel().getColumnCount();i++){
                colname[i]=controller.getModel().getColumnName(i);
                cmbModel.addElement(colname[i]);
            }       
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
        cmbSearch.setModel(cmbModel);
    }
    
    public void initTable(){
        try {
            controller.getModel().setResultSet(controller.getDao().getRsAll());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        tblDisplay.setModel(controller.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIDExemplaire = new javax.swing.JLabel();
        lblCodeBare = new javax.swing.JLabel();
        lblPrix = new javax.swing.JLabel();
        lblDateAchat = new javax.swing.JLabel();
        lblIDDocument = new javax.swing.JLabel();
        txtIDExemplaire = new javax.swing.JTextField();
        txtCodeBare = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        txtIDDocument = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        cmbSearch = new javax.swing.JComboBox<>();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtDateAchat = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplaire");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion Des Exemplaires");

        lblIDExemplaire.setText("ID Exemplaire:");

        lblCodeBare.setText("Code Bare:");

        lblPrix.setText("Prix:");

        lblDateAchat.setText("Date Achat:");

        lblIDDocument.setText("ID Document:");

        txtIDExemplaire.setEnabled(false);
        txtIDExemplaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDExemplaireActionPerformed(evt);
            }
        });

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblDisplayMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblDisplay);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnNew.setText("New");
        btnNew.setEnabled(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel2.add(btnFind);

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        btnUpdate1.setText("Update");
        btnUpdate1.setEnabled(false);
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate1);

        lblSearch.setText("Search by:");

        txtSearch.setEditable(false);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDExemplaire)
                            .addComponent(lblCodeBare)
                            .addComponent(lblPrix)
                            .addComponent(lblDateAchat)
                            .addComponent(lblIDDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDExemplaire)
                            .addComponent(txtIDDocument)
                            .addComponent(txtPrix)
                            .addComponent(txtCodeBare, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(txtDateAchat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addGap(26, 26, 26)
                        .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDExemplaire)
                    .addComponent(txtIDExemplaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodeBare)
                            .addComponent(txtCodeBare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrix)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateAchat)
                            .addComponent(txtDateAchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtIDExemplaire.setText("");
        txtCodeBare.setText("");
        txtPrix.setText("");
        txtDateAchat.setDate(null);
        txtIDDocument.setText("");
        
        btnSave.setEnabled(true);
        btnNew.setEnabled(false);
        
        //txtIDExemplaire.setEditable(false);
        txtIDDocument.setEditable(true);
        
        btnUpdate1.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if(getRecordValidation()== true){
                
                //int IDExemplaire=Integer.parseInt(txtIDExemplaire.getText().trim());
                CodeBare=txtCodeBare.getText().trim();
                Prix=Double.parseDouble(txtPrix.getText().trim());
                DateAchat=sdf.format(txtDateAchat.getDate());
                IdDoc=Integer.parseInt(txtIDDocument.getText().trim());
                
                //controller.getExemplaire().setIdExemplaire(IDExemplaire);
                controller.getExemplaire().setCodeBar(CodeBare);
                controller.getExemplaire().setPrix(Prix);
                controller.getExemplaire().setDateAchat(DateAchat);
                controller.getExemplaire().setIdDoc(IdDoc);
                
                try {
                    controller.getDao().insert(controller.getExemplaire());
                    JOptionPane.showMessageDialog(rootPane, "Exemplaire Enregistré");
                    btnNew.setEnabled(true);
                    btnSave.setEnabled(false);
                    initTable(); // afficher les donnees ajouteès directement dans la table
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane,ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExemplaireView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        txtSearch.setEditable(true);
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String colName= cmbSearch.getSelectedItem().toString();
        String word = txtSearch.getText().trim();
        
        try {
            ResultSet rs= controller.getDao().search(colName, word);
            controller.getModel().setResultSet(rs);
            tblDisplay.setModel(controller.getModel());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayMouseClicked
      
    }//GEN-LAST:event_tblDisplayMouseClicked

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
   
        try {
            if(getRecordValidation()== true){
                String IdEx=txtIDExemplaire.getText().trim();
                String CodeB=txtCodeBare.getText().trim();
                String Pr=txtPrix.getText().trim();
                String DateA=sdf.format(txtDateAchat.getDate());
                String IdD=txtIDDocument.getText().trim();
                
                controller.getExemplaire().setIdExemplaire(Integer.parseInt(IdEx));
                controller.getExemplaire().setCodeBar(CodeB);
                controller.getExemplaire().setPrix(Double.parseDouble(Pr));
                controller.getExemplaire().setDateAchat(DateA);
                controller.getExemplaire().setIdDoc(Integer.parseInt(IdD));
                
                try {
                    controller.getDao().update(controller.getExemplaire());
                    
                    JOptionPane.showMessageDialog(rootPane,"update succesful ");
                    initTable();
                    
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExemplaireView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void tblDisplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayMouseReleased
        int i= tblDisplay.getSelectedRow();

        
        txtCodeBare.setText(controller.getModel().getValueAt(i, 0).toString());
        txtIDExemplaire.setText(controller.getModel().getValueAt(i, 1).toString());
        txtPrix.setText(controller.getModel().getValueAt(i, 2).toString());
        // pour date achat de date string vers date
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)controller.getModel().getValueAt(i, 3));
            txtDateAchat.setDate(date);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane,ex);
        }
        txtIDDocument.setText(controller.getModel().getValueAt(i, 4).toString());

        btnUpdate1.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSave.setEnabled(false);
        btnNew.setEnabled(true);
        
        txtIDDocument.setEditable(false);  // u cant update
    }//GEN-LAST:event_tblDisplayMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String IDExemplaire = txtIDExemplaire.getText();
        controller.getExemplaire().setIdExemplaire(Integer.parseInt(IDExemplaire));
        
        try {
            controller.getDao().delete(controller.getExemplaire());
            JOptionPane.showMessageDialog(rootPane, "l'exemplaire a ete supprimé");
            initTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIDExemplaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDExemplaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDExemplaireActionPerformed

    /*    */
    
    public boolean getRecordValidation() throws SQLException{
        
        
        String DateAchat = sdf.format(txtDateAchat.getDate());
        
        
            
        
        if(controller.getValidation().isEmpty(txtCodeBare.getText().trim())){
            JOptionPane.showMessageDialog(rootPane, "entrer un code bare valide ");
            txtCodeBare.requestFocus();
            return false;
        }else if(controller.getValidation().isExist(txtCodeBare.getText().trim(),"exemplaire","codeBar")){
            JOptionPane.showMessageDialog(rootPane, "entrer un bar code unique ");
            txtPrix.requestFocus();
            return false;
        }

        else if(controller.getValidation().isEmpty(txtPrix.getText().trim())){
            JOptionPane.showMessageDialog(rootPane, "entrer un prix valide ");
            txtPrix.requestFocus();
            return false;
        }
        
                              
        
        else if(controller.getValidation().isEmpty(DateAchat) ){
            JOptionPane.showMessageDialog(rootPane, "entrer une date valide ");
            txtDateAchat.requestFocus();
            return false; 
        }
         
        else if(controller.getValidation().isEmpty(txtIDDocument.getText().trim())){
            JOptionPane.showMessageDialog(rootPane, "entrer un ID Document valide ");
            txtIDDocument.requestFocus();
            return false;
        }
        else if(!controller.getValidation().isExist(txtIDDocument.getText().trim(), "doc" , "idDoc")){
            JOptionPane.showMessageDialog(rootPane, "cet ID Doc n'existe pas");
            txtIDDocument.requestFocus();
            return false;
        }
        
        return true;
    }
      
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodeBare;
    private javax.swing.JLabel lblDateAchat;
    private javax.swing.JLabel lblIDDocument;
    private javax.swing.JLabel lblIDExemplaire;
    private javax.swing.JLabel lblPrix;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField txtCodeBare;
    private com.toedter.calendar.JDateChooser txtDateAchat;
    private javax.swing.JTextField txtIDDocument;
    private javax.swing.JTextField txtIDExemplaire;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
