/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ListeAttenteController;
import Models.ListeAttente;
import Models.Penalite;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author PC
 */
public class ListeAttenteView extends javax.swing.JFrame {
    ListeAttenteController lac = new ListeAttenteController();
    ArrayList<ListeAttente>  list ;
    DefaultTableModel model;
    int idDoc;
    /**
     * Creates new form penalite
     */
    public ListeAttenteView(int idDoc) {
        initComponents();
        this.idDoc =idDoc;
        viewPenalitesInTheTable() ; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        but_add_new2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cinF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setMaximumSize(new java.awt.Dimension(1070, 640));
        panel.setMinimumSize(new java.awt.Dimension(1070, 640));
        panel.setPreferredSize(new java.awt.Dimension(300, 450));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Penalite ID", "client cin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });

        jLabel5.setText("Chercher :");

        Add.setText("Ajouter");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        but_add_new2.setText("supprimer");
        but_add_new2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_add_new2MouseClicked(evt);
            }
        });
        but_add_new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_add_new2ActionPerformed(evt);
            }
        });

        jLabel6.setText("CIN Client");

        cinF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinFActionPerformed(evt);
            }
        });
        cinF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cinFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cinFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cinFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_add_new2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cinF, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_add_new2)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchFieldKeyTyped

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchFieldKeyReleased

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_searchFieldKeyPressed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        // TODO add your handling code here:
        boolean c=false;
        for(ListeAttente l :list){
        if(l.getCin().equals(cinF.getText())) c= true;
           }
        
        if(!lac.getLadao().isExistByCin(cinF.getText())){
        JOptionPane.showMessageDialog(null, "cin n'est pas valide");
        }
        else if (c){
            JOptionPane.showMessageDialog(null, "cin dja exist dans la list");
           }
        else{
            try {
                lac.getLadao().insert( new ListeAttente(idDoc, cinF.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(ListeAttenteView.class.getName()).log(Level.SEVERE, null, ex);
            }
            viewPenalitesInTheTable();
        }
       
      
    }//GEN-LAST:event_AddMouseClicked

    private void but_add_new2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_add_new2MouseClicked
        // TODO add your handling code here:
         if(table.getSelectedRow()==-1){
        JOptionPane.showMessageDialog(null, "Il n 'y a pas de ligne sélectionné");
        }
        else{
            lac.getLadao().delete((int) table.getValueAt(table.getSelectedRow(), 0));
            viewPenalitesInTheTable();
        }

    }//GEN-LAST:event_but_add_new2MouseClicked

    private void but_add_new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_add_new2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_add_new2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.getSelectedRow();
       

    }//GEN-LAST:event_tableMouseClicked

    private void cinFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinFActionPerformed

    private void cinFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinFKeyPressed

    private void cinFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinFKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cinFKeyReleased

    private void cinFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cinFKeyTyped

    
    
    
      private void search()
    {
        String keyword = searchField.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        table.setRowSorter(tr);
 
        tr.setRowFilter(RowFilter.regexFilter(keyword));
    }
      
  
    
    
    
      public void viewPenalitesInTheTable() 
    {
       
        
      

        list  =  lac.getLadao().getListeAttente(idDoc);
         model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
 
        Object[] row = new Object[2];
        int size = list == null ? 0 :  list.size();
        for(int i = 0; i<size; i++)
        {
            row[0] = list.get(i).getIdLA();
            row[1] = list.get(i).getCin();


           
            model.addRow(row);
           
        }
 
    }
    
      
//    public static void main(String[] args) {
//        ListeAttenteView listeAttenteView = new ListeAttenteView(1);
//        listeAttenteView.setVisible(true);
//    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton but_add_new2;
    private javax.swing.JTextField cinF;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
